### ISSUE TITLE
Dying on a Space station in orbit of gas giant causes time-out after bugged respawn and log out

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#161] opened 2020-06-01 16:41 UTC
So, i died on my space station (depressurization) and respawned in the void, i logged off and tried to log in again, but all i get is a Timeout from the server. a reinstallation of the pack didn't help and the logs only state the timeout, nothing else. is there a way to fix this? i would like to play again on the server... maybe a player data reset solves this (had the same problem a few weeks ago, a player data wipe helped)

**Comment by TheRedCreations** [comment] 2020-06-01 19:56
The Space station is in orbit of a gas giant. you can't spawn on such a planet. I have now the same problem cause Sunnys turret on his station(he said i'm trusted on that)

**Comment by Joey4213** [comment] 2020-06-01 20:52
ok so i need to go pick your guyes stuff up then right?

**Comment by SunnyM00n** [comment] 2020-06-01 20:55
nope, stuff already despawned (checked it with my backup account) sokar has to reset our player data, otherwise we can't play anymore

**Comment by Joey4213** [comment] 2020-06-01 20:58
rest in pieces D:

**Comment by Joey4213** [comment] 2020-06-05 10:00
#127 bump

**Comment by Joey4213** [comment] 2020-06-05 10:03
also needs closing as it was the same or similar glitch

**Comment by StargateMC** [comment] 2020-06-05 10:03
Awesome apparently a duplicate of #127

**Closed by StargateMC** 2020-06-05 10:03 UTC
