### ISSUE TITLE
Join server causes temporary server timeout

### ISSUE THREAD

**Issue by Joey4213** [StargateMC/IssueTracker#119] opened 2020-05-01 07:04 UTC
When I join the server it causes the server to have a temporary timeout...

causes client to not be able to connect including my own

**Comment by StargateMC** [comment] 2020-05-04 04:50
CustomnPCs bug. Been unable to identify the cause so far.. closing until we can reproduce it.

**Closed by StargateMC** 2020-05-04 04:50 UTC
