### ISSUE TITLE
Stargate Recipe Voting

### ISSUE THREAD

**Issue by SunnyM00n** [StargateMC/IssueTracker#213] opened 2020-06-16 14:31 UTC
Sokar suggested this: What Stargate recipes do you want? The current, very expensive ones or cheaper ones? Vote with 👍 for cheaper ones, Vote with 👎 to keep the new ones.

**Comment by DEVensiv** [comment] 2020-06-16 14:33
A stargate is a super high advanced tech therefore it should be expensive

**Comment by Joey4213** [comment] 2020-06-16 14:46
i agree with @DEVensiv but infact we never actually knew how to build/construct stargates to be cannon :D

**Comment by mainesi** [comment] 2020-06-16 14:59
Gates should be hard to build due to them being of ancient tech. Although I don’t understand why gate recipes are needed since only gate per world is allowed

**Comment by Joey4213** [comment] 2020-06-16 15:01
so this that a yes or no on it, we kinda need votes so i can know whether or not to change it

**Comment by mainesi** [comment] 2020-06-16 15:46
Well there is no option for neither so I can’t vote

**Comment by Joey4213** [comment] 2020-06-16 22:22
sure there this 😕

**Comment by draksterau** [comment] 2020-06-17 00:29
My personal opinion is that it should be more appealing to travel for an hour to a remote gate and steal it for your world than crafting a new one.... but that's just me.

If you're not happy with the current recipe, suggest alternatives and justify them.

**Comment by draksterau** [comment] 2020-06-18 07:40
Duplicate of https://github.com/StargateMC/IssueTracker/issues/211

**Closed by draksterau** 2020-06-18 07:40 UTC
